#!/bin/zsh


#Text coloring functions
function color {
    if tty -s
    then
        tput setaf $2
        echo "$1"
        tput sgr0
        return
    fi
    
    echo "$1"
}

function red {
    color "$1" 1
}

function yellow {
    color "$1" 3
}

function green {
    color "$1" 2
}


#Prompt to continue
function confirm {
    yellow "Press y to continue, any other key to exit"
	tput bel

    read -q "variable?"
    echo ""
    if [[ $variable != "y" && $variable != "Y" ]]
    then
        red "Exiting"
        say "Done"
        exit 0
    fi
    green "Continuing"
}


green "Getting previous commit..."
hashOfPreviousCommit=$(git log -n 1 --skip 1 --pretty=format:"%H")
previousCommitMessage=$(git log -n 1 --pretty=format:"%B" $hashOfPreviousCommit)


green "Previous commit message: \n\n$previousCommitMessage\n"
green "Merge down, using that message?"
confirm

hashTwoCommitsAgo=$(git log -n 1 --skip 2 --pretty=format:"%H")
git reset --soft $hashTwoCommitsAgo
git add -A && git commit -m "$previousCommitMessage"

green "Force-push to origin?"
confirm
git push -f origin 

green "Done"
say "Done"
