#!/bin/zsh
#Text coloring functions
function color {
    if tty -s
    then
        tput setaf $2
        echo "$1"
        tput sgr0
        return
    fi
    
    echo "$1"
}

function red {
    color "$1" 1
}

function yellow {
    color "$1" 3
}

function green {
    color "$1" 2
}


#Prompt to continue
function confirm {
    yellow "Press y to continue, any other key to exit"
	tput bel

    read -q "variable?"
    echo ""
    if [[ $variable != "y" && $variable != "Y" ]]
    then
        red "Exiting"
        say "Done"
        exit 0
    fi
    green "Continuing"
}


hashOfMergeBase=$(gitmergebase)
originalCommitMessage=$(git log --format=%B -n 1 $hashOfOriginalCommit)

green "Original commit message is: \n$originalCommitMessage"
green "Soft-reset to that hash?"

confirm 

git reset --soft $hashOfMergeBase