#!/bin/zsh


#Text coloring functions
function color {
    if tty -s
    then
        tput setaf $2
        echo "$1"
        tput sgr0
        return
    fi
    
    echo "$1"
}

function red {
    color "$1" 1
}

function yellow {
    color "$1" 3
}

function green {
    color "$1" 2
}


#Prompt to continue
function confirm {
    yellow "Press y to continue, any other key to exit"
	tput bel

    read -q "variable?"
    echo ""
    if [[ $variable != "y" && $variable != "Y" ]]
    then
        red "Exiting"
        say "Done"
        exit 0
    fi
    green "Continuing"
}


green "Getting merge base..."
currentBranch=$(git rev-parse --abbrev-ref HEAD)
parent=$(gitparent)
hashOfMergeBase=$(git merge-base $currentBranch $parent)
mergeBaseCommitMessage=$(git log --format=oneline -n 1 $hashOfMergeBase)


green "Merge base is $mergeBaseCommitMessage"
green "Proceed?"
confirm



green "Getting message of first commit..."
hashOfOriginalCommit=$(git rev-list $parent..HEAD | tail -1)
originalCommitMessage=$(git log --format=%B -n 1 $hashOfOriginalCommit)

green "Original commit message is: \n$originalCommitMessage"
green "Squash to original commit using that message?"

confirm 
git reset --soft $hashOfMergeBase
git add -A && git commit -m "$originalCommitMessage"

green "Force-push to origin?"
confirm
git push -f origin 

green "Done"
say "Done"
