#!/bin/zsh


#Text coloring functions
function color {
    if tty -s
    then
        tput setaf $2
        echo "$1"
        tput sgr0
        return
    fi
    
    echo "$1"
}

function red {
    color "$1" 1
}

function green {
    color "$1" 2
}

####################
## Script Contents #
####################

develBranches=($(git config scripts.develop))
if [ -z "$develBranches" ]; then
    red "Specify which branches are develop branches using git config. Example:\ngit config scripts.develop devel-4.0 devel-2.9"
    exit 1
fi

for develBranch in $develBranches
do
    green "Pulling $develBranch"
    git checkout $develBranch
    git pull
done

green "Done!"