#!/bin/zsh

#Text coloring functions
function color {
    if tty -s
    then
        tput setaf $2
        echo "$1"
        tput sgr0
        return
    fi
    
    echo "$1"
}

function red {
    color "$1" 1
}

function yellow {
    color "$1" 3
}

function green {
    color "$1" 2
}


#Prompt to continue
function confirm {
    yellow "Press y to continue, any other key to exit"
    tput bel

    read -q "variable?"
    echo ""
    if [[ $variable != "y" && $variable != "Y" ]]
    then
        red "Exiting"
        exit 0
    fi
    green "Continuing"
}

#Get the parent process ID
match=$(ps -efw | grep $1 | grep -v grep | grep -v killparent | tail -1)
parentProcessId=$(echo $match | awk '{print $3}')

#Confirm
green "Matching process:"
echo $match
echo ""
green "kill $parentProcessId?"
confirm

#Kill
kill $parentProcessId
